# Домашняя работа

### Импорт библиотек

In [199]:
import math
import numpy as np

### Перевод градусов в радианы и наоборот

In [ ]:
d = 180
r = math.radians(d)
print(f'{d} градусов = {r} радиан')

r = math.pi
d = math.degrees(r)
print(f'{r} радиан = {d} градусов')

180 градусов = 3.141592653589793 радиан
3.141592653589793 радиан = 180.0 градусов


### Примеры создания массивов:

In [ ]:
# Создание массива из одномерного списка
l = [1, 2, 3, 4, 5]
arr = np.array(l)
print(arr)

[1 2 3 4 5]


In [206]:
l = [[1.5, 2, 3], [4, 5.7, 6]]
arr = np.array(l)
print(arr)

[[1.5 2.  3. ]
 [4.  5.7 6. ]]


In [211]:
# Массив из нулей
z1 = np.zeros(5)
print(f'{z1}\n')

z2 = np.zeros((3, 4))
print(f'{z2}\n')

z_int = np.zeros(5, dtype=int)
print(z_int)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0 0 0 0 0]


In [ ]:
# Массив из единиц
o = np.ones((2, 3))
print(f'{o}\n')

# Единичная матрица
identity = np.eye(3)
print(identity)

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [212]:
# Диапазон
arr1 = np.arange(0, 10, 2)
print(f'{arr1}\n')

arr2 = np.arange(0, 1, 0.1)
print(arr2)

[0 2 4 6 8]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [213]:
# Равномерно распределенные числа
lin_arr = np.linspace(0, 10, 5)
print(lin_arr)

[ 0.   2.5  5.   7.5 10. ]


### Демонстрация атрибутов

In [221]:
arr = np.arange(0, 20, 2)
print(arr.shape)

reshaped = arr.reshape(2, 5)
print(reshaped.shape)

print('Тип данных:', arr.dtype)
print('Размерность:', arr.ndim)
print('Общее количество элементов:', arr.size)

(10,)
(2, 5)
Тип данных: int64
Размерность: 1
Общее количество элементов: 10


### Примеры индексирования и срезов

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print('Исходный массив:', arr1)

# Отдельные элементы
print('1 эл:', arr1[0])
print('5 эл:', arr1[4])
print('Последний эл:', arr1[-1])

# Срезы
print('3 - 5 эл:', arr1[2:5])
print('1 - 4 эл:', arr1[:4])
print('6 - 9 эл:', arr1[5:])
print('Каждый 2:', arr1[::2])
print('Реверс:', arr1[::-1])

Исходный массив: [10 20 30 40 50 60 70 80 90]
1 эл: 10
5 эл: 50
Последний эл: 90
3 - 5 эл: [30 40 50]
1 - 4 эл: [10 20 30 40]
6 - 9 эл: [60 70 80 90]
Каждый 2: [10 30 50 70 90]
Реверс: [90 80 70 60 50 40 30 20 10]


In [ ]:
arr2 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print('Исходная матрица:')
print(arr2)

# Отдельные элементы
print('Строка 0, столбец 0:', arr2[0, 0])
print('Строка 2, столбец 1:', arr2[2, 1])
print('Последняя строка, последний столбец:', arr2[-1, -1])

# Срезы
print('Первая строка:', arr2[0, :])
print('Второй столбец:', arr2[:, 1])
print('Последняя строка:', arr2[-1, :])

# Подматрицы
print('Середина:\n', arr2[1:3, 1:3])
print('Лев верх:\n', arr2[:2, :2])
print('Лев верх ч-з одного:\n', arr2[::2, ::2])

Исходная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Строка 0, столбец 0: 1
Строка 2, столбец 1: 10
Последняя строка, последний столбец: 16
Первая строка: [1 2 3 4]
Второй столбец: [ 2  6 10 14]
Последняя строка: [13 14 15 16]
Середина:
 [[ 6  7]
 [10 11]]
Лев верх:
 [[1 2]
 [5 6]]
Лев верх ч-з одного:
 [[ 1  3]
 [ 9 11]]


### Примеры векторных операций и базовых статистик

In [231]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('Матрица A:')
print(a)
print('Матрица B:')
print(b)

# Поэлементные операции с матрицами
print('\nA + B:')
print(a + b)


print('\nA * B:')
print(a * b)


print('\nA ** 2:')
print(a ** 2)

Матрица A:
[[1 2]
 [3 4]]
Матрица B:
[[5 6]
 [7 8]]

A + B:
[[ 6  8]
 [10 12]]

A * B:
[[ 5 12]
 [21 32]]

A ** 2:
[[ 1  4]
 [ 9 16]]


In [238]:
data = np.array([2, 5, 8, 9, 4, 4, 3, 7, 2, 2, 2, 1, 9, 2, 4, 6])
print('Данные:', data)

# Базовые статистики
print('Минимальное значение:', np.min(data))
print('Максимальное значение:', np.max(data))
print('Среднее значение:', np.mean(data))
print('Медиана:', np.median(data))
print('Стандартное отклонение:', np.std(data))
print('Дисперсия:', np.var(data))
print('Квантили:', np.quantile(data, [0.25, 0.5, 0.75]))
print('Мода:', np.bincount(data).argmax()) # 3

Данные: [2 5 8 9 4 4 3 7 2 2 2 1 9 2 4 6]
Минимальное значение: 1
Максимальное значение: 9
Среднее значение: 4.375
Медиана: 4.0
Стандартное отклонение: 2.595067436503337
Дисперсия: 6.734375
Квантили: [2.   4.   6.25]
Мода: 2
